export const GOOGLE_FONTS = [
  // --- Originais (mantidas) ---
  { name: 'Inter', value: 'Inter', type: 'sans-serif' },
  { name: 'Roboto', value: 'Roboto', type: 'sans-serif' },
  { name: 'Merriweather', value: 'Merriweather', type: 'serif' },
  { name: 'Fira Code', value: 'Fira Code', type: 'monospace' },
  { name: 'Montserrat', value: 'Montserrat', type: 'sans-serif' },
  { name: 'Open Sans', value: 'Open Sans', type: 'sans-serif' },
  { name: 'Lato', value: 'Lato', type: 'sans-serif' },
  { name: 'Source Sans Pro', value: 'Source Sans Pro', type: 'sans-serif' },

  { name: 'Poppins', value: 'Poppins', type: 'sans-serif' },
  { name: 'Nunito', value: 'Nunito', type: 'sans-serif' },
  { name: 'Raleway', value: 'Raleway', type: 'sans-serif' },
  { name: 'Ubuntu', value: 'Ubuntu', type: 'sans-serif' },
  { name: 'PT Sans', value: 'PT Sans', type: 'sans-serif' },
  { name: 'Karla', value: 'Karla', type: 'sans-serif' },
  { name: 'Nunito Sans', value: 'Nunito Sans', type: 'sans-serif' },
  { name: 'Work Sans', value: 'Work Sans', type: 'sans-serif' },
  { name: 'Space Grotesk', value: 'Space Grotesk', type: 'sans-serif' },
  { name: 'Syne', value: 'Syne', type: 'sans-serif' },
  { name: 'Fahkwang', value: 'Fahkwang', type: 'sans-serif' },
  { name: 'Droid Sans', value: 'Droid Sans', type: 'sans-serif' },

  { name: 'Playfair Display', value: 'Playfair Display', type: 'serif' },
  { name: 'Lora', value: 'Lora', type: 'serif' },
  { name: 'Source Serif Pro', value: 'Source Serif Pro', type: 'serif' },
  { name: 'Libre Baskerville', value: 'Libre Baskerville', type: 'serif' },
  { name: 'Noto Serif', value: 'Noto Serif', type: 'serif' },
  { name: 'Josefin Slab', value: 'Josefin Slab', type: 'serif' },
  { name: 'Arvo', value: 'Arvo', type: 'serif' },
  { name: 'Vollkorn', value: 'Vollkorn', type: 'serif' },
  { name: 'PT Serif', value: 'PT Serif', type: 'serif' },
  { name: 'Old Standard TT', value: 'Old Standard TT', type: 'serif' },

  { name: 'Fira Code', value: 'Fira Code', type: 'monospace' },
  { name: 'Inconsolata', value: 'Inconsolata', type: 'monospace' },
  { name: 'JetBrains Mono', value: 'JetBrains Mono', type: 'monospace' },
  { name: 'Ubuntu Mono', value: 'Ubuntu Mono', type: 'monospace' },
  { name: 'Syne Mono', value: 'Syne Mono', type: 'monospace' },

  { name: 'Oswald', value: 'Oswald', type: 'display' },
  { name: 'Bebas Neue', value: 'Bebas Neue', type: 'display' },
  { name: 'Lobster', value: 'Lobster', type: 'display' },
  { name: 'Anton', value: 'Anton', type: 'display' },
  { name: 'Abril Fatface', value: 'Abril Fatface', type: 'display' },
  { name: 'Cinzel', value: 'Cinzel', type: 'display' },
  { name: 'Righteous', value: 'Righteous', type: 'display' },
  { name: 'Pacifico', value: 'Pacifico', type: 'handwriting' },
  { name: 'Caveat', value: 'Caveat', type: 'handwriting' },
  { name: 'Dancing Script', value: 'Dancing Script', type: 'handwriting' },
  { name: 'Shadows Into Light', value: 'Shadows Into Light', type: 'handwriting' },

  // --- Sans-serif adicionais (bem usados) ---
  { name: 'Noto Sans', value: 'Noto Sans', type: 'sans-serif' },
  { name: 'Noto Sans JP', value: 'Noto Sans JP', type: 'sans-serif' },
  { name: 'Noto Sans KR', value: 'Noto Sans KR', type: 'sans-serif' },
  { name: 'Noto Sans SC', value: 'Noto Sans SC', type: 'sans-serif' },
  { name: 'Noto Sans TC', value: 'Noto Sans TC', type: 'sans-serif' },
  { name: 'Roboto Condensed', value: 'Roboto Condensed', type: 'sans-serif' },
  { name: 'Roboto Flex', value: 'Roboto Flex', type: 'sans-serif' },
  { name: 'Manrope', value: 'Manrope', type: 'sans-serif' },
  { name: 'Barlow', value: 'Barlow', type: 'sans-serif' },
  { name: 'Barlow Condensed', value: 'Barlow Condensed', type: 'sans-serif' },
  { name: 'Archivo', value: 'Archivo', type: 'sans-serif' },
  { name: 'Archivo Narrow', value: 'Archivo Narrow', type: 'sans-serif' },
  { name: 'Heebo', value: 'Heebo', type: 'sans-serif' },
  { name: 'Mukta', value: 'Mukta', type: 'sans-serif' },
  { name: 'Mulish', value: 'Mulish', type: 'sans-serif' },
  { name: 'Titillium Web', value: 'Titillium Web', type: 'sans-serif' },
  { name: 'Hind', value: 'Hind', type: 'sans-serif' },
  { name: 'Hind Siliguri', value: 'Hind Siliguri', type: 'sans-serif' },
  { name: 'IBM Plex Sans', value: 'IBM Plex Sans', type: 'sans-serif' },
  { name: 'IBM Plex Sans Condensed', value: 'IBM Plex Sans Condensed', type: 'sans-serif' },
  { name: 'IBM Plex Sans Arabic', value: 'IBM Plex Sans Arabic', type: 'sans-serif' },
  { name: 'IBM Plex Sans Thai', value: 'IBM Plex Sans Thai', type: 'sans-serif' },
  { name: 'IBM Plex Sans Devanagari', value: 'IBM Plex Sans Devanagari', type: 'sans-serif' },
  { name: 'Plus Jakarta Sans', value: 'Plus Jakarta Sans', type: 'sans-serif' },
  { name: 'Quicksand', value: 'Quicksand', type: 'sans-serif' },
  { name: 'Muli', value: 'Muli', type: 'sans-serif' },
  { name: 'Asap', value: 'Asap', type: 'sans-serif' },
  { name: 'Asap Condensed', value: 'Asap Condensed', type: 'sans-serif' },
  { name: 'Cabin', value: 'Cabin', type: 'sans-serif' },
  { name: 'Fjalla One', value: 'Fjalla One', type: 'sans-serif' },
  { name: 'Domine', value: 'Domine', type: 'serif' }, // muito usada em texto, mas já deixo aqui
  { name: 'Maven Pro', value: 'Maven Pro', type: 'sans-serif' },
  { name: 'Exo 2', value: 'Exo 2', type: 'sans-serif' },
  { name: 'Baloo 2', value: 'Baloo 2', type: 'sans-serif' },
  { name: 'Spoqa Han Sans Neo', value: 'Spoqa Han Sans Neo', type: 'sans-serif' }, // similar a Noto, popular em interfaces
  { name: 'Jost', value: 'Jost', type: 'sans-serif' },
  { name: 'Urbanist', value: 'Urbanist', type: 'sans-serif' },
  { name: 'Outfit', value: 'Outfit', type: 'sans-serif' },
  { name: 'Lexend', value: 'Lexend', type: 'sans-serif' },
  { name: 'Lexend Deca', value: 'Lexend Deca', type: 'sans-serif' },
  { name: 'Prompt', value: 'Prompt', type: 'sans-serif' },
  { name: 'Sarala', value: 'Sarala', type: 'sans-serif' },
  { name: 'Public Sans', value: 'Public Sans', type: 'sans-serif' },
  { name: 'Red Hat Display', value: 'Red Hat Display', type: 'sans-serif' },
  { name: 'Red Hat Text', value: 'Red Hat Text', type: 'sans-serif' },
  { name: 'DM Sans', value: 'DM Sans', type: 'sans-serif' },
  { name: 'DM Mono', value: 'DM Mono', type: 'monospace' },

  // --- Serif adicionais ---
  { name: 'Roboto Slab', value: 'Roboto Slab', type: 'serif' },
  { name: 'Merriweather Sans', value: 'Merriweather Sans', type: 'sans-serif' },
  { name: 'Crimson Text', value: 'Crimson Text', type: 'serif' },
  { name: 'Crimson Pro', value: 'Crimson Pro', type: 'serif' },
  { name: 'Cormorant Garamond', value: 'Cormorant Garamond', type: 'serif' },
  { name: 'Cormorant', value: 'Cormorant', type: 'serif' },
  { name: 'Cormorant Infant', value: 'Cormorant Infant', type: 'serif' },
  { name: 'EB Garamond', value: 'EB Garamond', type: 'serif' },
  { name: 'Cardo', value: 'Cardo', type: 'serif' },
  { name: 'Georgia Pro', value: 'Georgia Pro', type: 'serif' }, // similar, não é exatamente Google Fonts mas muitos usam equivalente
  { name: 'Alegreya', value: 'Alegreya', type: 'serif' },
  { name: 'Alegreya SC', value: 'Alegreya SC', type: 'serif' },
  { name: 'Alegreya Sans', value: 'Alegreya Sans', type: 'sans-serif' },
  { name: 'Bitter', value: 'Bitter', type: 'serif' },
  { name: 'Spectral', value: 'Spectral', type: 'serif' },
  { name: 'Georgia', value: 'Georgia', type: 'serif' }, // fallback de sistema
  { name: 'Prata', value: 'Prata', type: 'serif' },
  { name: 'DM Serif Display', value: 'DM Serif Display', type: 'serif' },
  { name: 'DM Serif Text', value: 'DM Serif Text', type: 'serif' },
  { name: 'Rosario', value: 'Rosario', type: 'serif' },

  // --- Monospace adicionais ---
  { name: 'Roboto Mono', value: 'Roboto Mono', type: 'monospace' },
  { name: 'Source Code Pro', value: 'Source Code Pro', type: 'monospace' },
  { name: 'Cascadia Code', value: 'Cascadia Code', type: 'monospace' }, // não é Google Fonts, mas muito usada
  { name: 'Courier Prime', value: 'Courier Prime', type: 'monospace' },
  { name: 'Space Mono', value: 'Space Mono', type: 'monospace' },
  { name: 'Anonymous Pro', value: 'Anonymous Pro', type: 'monospace' },

  // --- Display / Handwriting extras ---
  { name: 'Josefin Sans', value: 'Josefin Sans', type: 'display' },
  { name: 'Playfair Display SC', value: 'Playfair Display SC', type: 'display' },
  { name: 'Amatic SC', value: 'Amatic SC', type: 'display' },
  { name: 'Alfa Slab One', value: 'Alfa Slab One', type: 'display' },
  { name: 'Poiret One', value: 'Poiret One', type: 'display' },
  { name: 'Bangers', value: 'Bangers', type: 'display' },
  { name: 'Fredoka', value: 'Fredoka', type: 'display' },
  { name: 'Yanone Kaffeesatz', value: 'Yanone Kaffeesatz', type: 'display' },
  { name: 'Chewy', value: 'Chewy', type: 'display' },
  { name: 'Ga Maamli', value: 'Ga Maamli', type: 'display' },
  { name: 'Great Vibes', value: 'Great Vibes', type: 'handwriting' },
  { name: 'Satisfy', value: 'Satisfy', type: 'handwriting' },
  { name: 'Gloria Hallelujah', value: 'Gloria Hallelujah', type: 'handwriting' },
  { name: 'Indie Flower', value: 'Indie Flower', type: 'handwriting' },
  { name: 'Patrick Hand', value: 'Patrick Hand', type: 'handwriting' },
  { name: 'Amiri', value: 'Amiri', type: 'serif' }, // árabe + latino
  { name: 'Tajawal', value: 'Tajawal', type: 'sans-serif' }, // árabe
  { name: 'Cairo', value: 'Cairo', type: 'sans-serif' },
  { name: 'Kufam', value: 'Kufam', type: 'sans-serif' },
]
