const GRADIENTS = [
  { name: 'Midnight', value: 'linear-gradient(to top, #09203f 0%, #537895 100%)' },
  { name: 'Hyper', value: 'linear-gradient(to right, #ec008c, #fc6767)' },
  { name: 'Oceanic', value: 'linear-gradient(120deg, #89f7fe 0%, #66a6ff 100%)' },
  { name: 'Peachy', value: 'linear-gradient(to right, #ffecd2 0%, #fcb69f 100%)' },
  { name: 'Emerald', value: 'linear-gradient(to right, #43e97b 0%, #38f9d7 100%)' },
  { name: 'Violet', value: 'linear-gradient(to top, #5f72bd 0%, #9b23ea 100%)' },
  { name: 'Sunset', value: 'linear-gradient(to right, #fa709a 0%, #fee140 100%)' },
  { name: 'Forest', value: 'linear-gradient(to right, #134e5e 0%, #71b280 100%)' },
  { name: 'Lavender', value: 'linear-gradient(to right, #e0c3fc 0%, #8ec5fc 100%)' },
  { name: 'Crimson', value: 'linear-gradient(to right, #f093fb 0%, #f5576c 100%)' },
  { name: 'Aurora', value: 'linear-gradient(to right, #667eea 0%, #764ba2 100%)' },
  { name: 'Tropical', value: 'linear-gradient(to right, #f093fb 0%, #f5576c 50%, #4facfe 100%)' },
  { name: 'Mint', value: 'linear-gradient(to right, #a8edea 0%, #fed6e3 100%)' },
  { name: 'Cosmic', value: 'linear-gradient(to right, #fa709a 0%, #fee140 50%, #30cfd0 100%)' },
  { name: 'Royal', value: 'linear-gradient(to right, #141e30 0%, #243b55 100%)' },
  { name: 'Coral', value: 'linear-gradient(to right, #ff9a9e 0%, #fecfef 50%, #fecfef 100%)' },
  { name: 'Neon', value: 'linear-gradient(to right, #00c9ff 0%, #92fe9d 100%)' },
  {
    name: 'Purple Dream',
    value: 'linear-gradient(to right, #667eea 0%, #764ba2 50%, #f093fb 100%)',
  },
  { name: 'Golden Hour', value: 'linear-gradient(to right, #f6d365 0%, #fda085 100%)' },
  { name: 'Deep Blue', value: 'linear-gradient(to right, #1e3c72 0%, #2a5298 100%)' },
  {
    name: 'Pink Lemonade',
    value: 'linear-gradient(to right, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)',
  },
  { name: 'Electric', value: 'linear-gradient(to right, #f093fb 0%, #4facfe 100%)' },
  { name: 'Mystic', value: 'linear-gradient(to right, #a8caba 0%, #5d4e75 100%)' },
  { name: 'Fire', value: 'linear-gradient(to right, #f12711 0%, #f5af19 100%)' },
  {
    name: 'Ocean Depth',
    value: 'linear-gradient(to right, #134e5e 0%, #71b280 50%, #134e5e 100%)',
  },
  { name: 'Solid Black', value: '#000000' },
  { name: 'Solid White', value: '#ffffff' },
  { name: 'Solid Gray', value: '#1a1a1a' },
  { name: 'Solid Dark Blue', value: '#0a1929' },
  { name: 'Transparent', value: 'transparent' },
]

const LANGUAGES = [
  'javascript',
  'typescript',
  'python',
  'java',
  'html',
  'css',
  'json',
  'sql',
  'bash',
  'go',
  'rust',
  'cpp',
  'c',
  'csharp',
  'php',
  'ruby',
  'swift',
  'kotlin',
  'dart',
  'scala',
  'r',
  'matlab',
  'lua',
  'perl',
  'shell',
  'powershell',
  'yaml',
  'toml',
  'xml',
  'markdown',
  'dockerfile',
  'nginx',
  'apache',
  'graphql',
  'vue',
  'svelte',
  'jsx',
  'tsx',
  'sass',
  'less',
  'stylus',
  'coffeescript',
  'elm',
  'haskell',
  'clojure',
  'erlang',
  'elixir',
  'ocaml',
  'fsharp',
  'vbnet',
  'objectivec',
]

const FONT_FAMILIES = [
  'JetBrains Mono',
  'Fira Code',
  'Source Code Pro',
  'Consolas',
  'Monaco',
  'Courier New',
  'Roboto Mono',
  'Inconsolata',
  'Cascadia Code',
  'Hack',
  'IBM Plex Mono',
  'Space Mono',
  'Ubuntu Mono',
  'Droid Sans Mono',
  'Menlo',
  'SF Mono',
]

const CODE_THEMES = [
  { name: 'VS Code Dark+', value: 'vscDarkPlus' },
  { name: 'Dracula', value: 'dracula' },
  { name: 'One Dark', value: 'oneDark' },
  { name: 'One Light', value: 'oneLight' },
  { name: 'Omni', value: 'darcula' },
  { name: 'Material Dark', value: 'materialDark' },
  { name: 'Material Oceanic', value: 'materialOceanic' },
  { name: 'Night Owl', value: 'nightOwl' },
  { name: 'Nord', value: 'nord' },
  { name: 'Gruvbox Dark', value: 'gruvboxDark' },
  { name: 'Gruvbox Light', value: 'gruvboxLight' },
  { name: 'Synthwave 84', value: 'synthwave84' },
  { name: 'Shades of Purple', value: 'shadesOfPurple' },
  { name: 'Lucario', value: 'lucario' },
  { name: 'Coldark Dark', value: 'coldarkDark' },
  { name: 'Coldark Cold', value: 'coldarkCold' },
  { name: 'A11y Dark', value: 'a11yDark' },
  { name: 'Atom Dark', value: 'atomDark' },
  { name: 'Duotone Dark', value: 'duotoneDark' },
  { name: 'Duotone Space', value: 'duotoneSpace' },
  { name: 'Duotone Earth', value: 'duotoneEarth' },
  { name: 'Duotone Forest', value: 'duotoneForest' },
  { name: 'Duotone Sea', value: 'duotoneSea' },
  { name: 'Holi Theme', value: 'holiTheme' },
  { name: 'Hopscotch', value: 'hopscotch' },
  { name: 'Twilight', value: 'twilight' },
  { name: 'Tomorrow', value: 'tomorrow' },
  { name: 'Solarized Dark Atom', value: 'solarizedDarkAtom' },
  { name: 'Solarized Light', value: 'solarizedlight' },
  { name: 'VS Dark', value: 'vsDark' },
  { name: 'VS', value: 'vs' },
  { name: 'Dark', value: 'dark' },
  { name: 'Okaidia', value: 'okaidia' },
  { name: 'Coy', value: 'coy' },
  { name: 'Coy Without Shadows', value: 'coyWithoutShadows' },
  { name: 'Funky', value: 'funky' },
  { name: 'Pojoaque', value: 'pojoaque' },
  { name: 'Xonokai', value: 'xonokai' },
  { name: 'Z Touch', value: 'zTouch' },
]

export { CODE_THEMES, FONT_FAMILIES, GRADIENTS, LANGUAGES }
