export const PRESET_COLORS = [
  '#000000',
  '#64748b',
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#10b981',
  '#3b82f6',
  '#8b5cf6',
  '#d946ef',
]
export const PRESET_HIGHLIGHTS = ['#fef08a', '#bbf7d0', '#bfdbfe', '#fbcfe8', '#e2e8f0']
export const PRESET_EDITOR_CONFIG: {
  [key in Exclude<PresetEditorVisualConfig, 'custom'>]: VisualEditorCustom[]
} = {
  complete: [
    { key: 'undo-redo', order: 1, component: 'undo-redo' },
    { key: 'vertical-1', order: 2, component: 'vertical' },
    { key: 'typography', order: 3, component: 'typography' },
    { key: 'font-size', order: 4, component: 'font-size' },
    { key: 'bold', order: 5, component: 'bold' },
    { key: 'italic', order: 6, component: 'italic' },
    { key: 'underline', order: 7, component: 'underline' },
    { key: 'strikethrough', order: 8, component: 'strikethrough' },
    { key: 'vertical-2', order: 9, component: 'vertical' },
    { key: 'text-color', order: 10, component: 'text-color' },
    { key: 'text-highlight', order: 11, component: 'text-highlight' },
    { key: 'vertical-3', order: 12, component: 'vertical' },
    { key: 'text-align', order: 13, component: 'text-align' },
    { key: 'vertical-4', order: 14, component: 'vertical' },
    { key: 'bullet-list', order: 15, component: 'bullet-list' },
    { key: 'ordered-list', order: 16, component: 'ordered-list' },
    { key: 'task-list', order: 17, component: 'task-list' },
    { key: 'vertical-5', order: 18, component: 'vertical' },
    { key: 'link', order: 19, component: 'link' },
    { key: 'table', order: 20, component: 'table' },
    { key: 'image', order: 21, component: 'image' },
    { key: 'horizontal-rule', order: 22, component: 'horizontal-rule' },
    { key: 'vertical-6', order: 23, component: 'vertical' },
    { key: 'variables', order: 24, component: 'variables' },
  ],
  minimal: [
    { key: 'bold', order: 1, component: 'bold' },
    { key: 'italic', order: 2, component: 'italic' },
    { key: 'underline', order: 3, component: 'underline' },
    { key: 'strikethrough', order: 4, component: 'strikethrough' },
    { key: 'font-size', order: 5, component: 'font-size' },
    { key: 'vertical-3', order: 6, component: 'vertical' },
    { key: 'text-color', order: 7, component: 'text-color' },
    { key: 'text-highlight', order: 8, component: 'text-highlight' },
    { key: 'variables', order: 9, component: 'variables' },
    { key: 'vertical-4', order: 10, component: 'vertical' },
    { key: 'text-align', order: 11, component: 'text-align' },
    { key: 'vertical-5', order: 12, component: 'vertical' },
  ],
}
